#!/usr/bin/env python3
"""
Generate the repository README and one README per problem folder.

Each problem README embeds the write-up itself: PDF reports are rasterised
page-by-page into `<folder>/.report/` and inlined as images, Markdown-only
write-ups are converted to GitHub-flavoured Markdown and inlined as text.
Nothing here is meant to be edited by hand - edit the report, or
`tools/problems.json`, and re-run:

    python3 tools/build_readmes.py

Options:
    --compile   recompile any .typ whose .pdf is missing or out of date
    --dpi N     rasterisation resolution for report pages (default 150)
    --check     exit non-zero if the generated files are out of date

Requires: poppler (for `pdftoppm`), plus `typst` if you pass --compile.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
META = Path(__file__).resolve().parent / "problems.json"
PAGES_DIR = ".report"
PNG_PAGE_BUDGET = 400 * 1024  # above this a page is re-rendered as JPEG
BANNER = "<!-- AUTO-GENERATED by tools/build_readmes.py - edit the report or tools/problems.json, then re-run. -->"


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------

def have(tool: str) -> bool:
    return shutil.which(tool) is not None


def page_sort(paths) -> list[Path]:
    """Sort page-1 ... page-10 numerically, not lexically."""
    return sorted(paths, key=lambda p: int(re.search(r"(\d+)$", p.stem).group(1)))


def rel(path: Path, start: Path) -> str:
    """URL-ish relative path suitable for a Markdown link."""
    return path.relative_to(start).as_posix().replace(" ", "%20")


# --------------------------------------------------------------------------
# report discovery, compilation, rasterisation
# --------------------------------------------------------------------------

def discover_report(folder: Path) -> dict:
    """Pick the main write-up for a folder, and list any supplementary ones."""
    typs = sorted(p for p in folder.glob("*.typ") if p.name != "lib.typ")
    pdfs = sorted(folder.glob("*.pdf"))
    mds = sorted(p for p in folder.glob("*.md") if p.name.lower() != "readme.md")

    source = typs[0] if typs else (mds[0] if mds else None)
    pdf = None
    if source is not None:
        pdf = next((p for p in pdfs if p.stem == source.stem), None)
    if pdf is None and len(pdfs) == 1:
        pdf = pdfs[0]
    if pdf is None and pdfs:
        pdf = max(pdfs, key=lambda p: p.stat().st_size)

    used = {p for p in (source, pdf) if p is not None}
    extras = [p for p in typs + mds + pdfs if p not in used and p.suffix != ".typ"]
    # a supplementary md that has its own pdf: keep only the pdf
    extra_stems = {p.stem for p in extras if p.suffix == ".pdf"}
    extras = [p for p in extras if not (p.suffix == ".md" and p.stem in extra_stems)]
    return {"source": source, "pdf": pdf, "extras": sorted(set(extras))}


def sha(*blobs: bytes) -> str:
    h = hashlib.sha256()
    for blob in blobs:
        h.update(blob)
    return h.hexdigest()


def source_sha(source: Path) -> str:
    """Fingerprint a report source, template included."""
    blobs = [source.read_bytes()]
    lib = source.parent / "lib.typ"
    if source.suffix == ".typ" and lib.exists():
        blobs.append(lib.read_bytes())
    return sha(*blobs)


def stamp_file(pdf: Path) -> Path:
    return pdf.parent / PAGES_DIR / pdf.stem / ".stamp"


def read_stamp(pdf: Path) -> dict:
    try:
        return json.loads(stamp_file(pdf).read_text())
    except (OSError, ValueError):
        return {}


def write_stamp(pdf: Path, **fields) -> None:
    path = stamp_file(pdf)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({**read_stamp(pdf), **fields}, indent=2) + "\n")


def compile_typst(source: Path | None, pdf: Path | None) -> Path | None:
    """Recompile a .typ whose source has changed since the last build.

    Staleness is decided by hashing the source (and its lib.typ), not by mtime -
    a fresh `git clone` or CI checkout has no useful mtimes, and the Typst
    template stamps today's date into the PDF, so an mtime-driven rebuild would
    rewrite every report on every run.
    """
    if source is None or source.suffix != ".typ":
        return pdf
    target = pdf or source.with_suffix(".pdf")
    current = source_sha(source)
    recorded = read_stamp(target).get("src_sha")

    if target.exists() and recorded is None:
        # First build against an already-compiled PDF: trust it, just record it.
        write_stamp(target, src_sha=current)
        return target
    if target.exists() and recorded == current:
        return target
    if not have("typst"):
        print(f"  ! typst not installed, skipping compile of {source.name}", file=sys.stderr)
        return pdf
    print(f"  typst compile {source.name}")
    subprocess.run(["typst", "compile", source.name, target.name],
                   cwd=source.parent, check=True)
    write_stamp(target, src_sha=current)
    return target


def rasterise(pdf: Path, dpi: int) -> list[Path]:
    """Render every page of `pdf` to `<folder>/.report/<stem>/page-N.png`, cached."""
    out = pdf.parent / PAGES_DIR / pdf.stem
    existing = lambda: page_sort(p for p in out.glob("page-*") if p.suffix in (".png", ".jpg"))

    pdf_sha = sha(pdf.read_bytes())
    stamp = read_stamp(pdf)
    if stamp.get("pdf_sha") == pdf_sha and stamp.get("dpi") == dpi and existing():
        return existing()

    if not have("pdftoppm"):
        print(f"  ! pdftoppm not installed, cannot render {pdf.name}", file=sys.stderr)
        return existing()

    for stale in out.glob("page-*"):
        stale.unlink()
    out.mkdir(parents=True, exist_ok=True)

    def render(fmt: str) -> list[Path]:
        opts = ["-png"] if fmt == "png" else ["-jpeg", "-jpegopt", "quality=82"]
        subprocess.run(["pdftoppm", "-r", str(dpi), *opts, "-aa", "yes", "-aaVector", "yes",
                        str(pdf), str(out / "page")], check=True)
        return page_sort(out.glob(f"page-*.{fmt}"))

    print(f"  rendering {pdf.name} -> {PAGES_DIR}/{pdf.stem}/ @ {dpi}dpi")
    pages = render("png")
    # Scanned / photographic pages balloon as PNG; fall back to JPEG for those.
    if pages and sum(p.stat().st_size for p in pages) / len(pages) > PNG_PAGE_BUDGET:
        print("    (photographic pages - re-rendering as JPEG)")
        for page in pages:
            page.unlink()
        pages = render("jpg")

    write_stamp(pdf, pdf_sha=pdf_sha, dpi=dpi)
    return pages


# --------------------------------------------------------------------------
# pandoc-flavoured Markdown -> GitHub Markdown
# --------------------------------------------------------------------------

CENTER_RE = re.compile(r"\\begin\{center\}(.*?)\\end\{center\}", re.S)
GRAPHIC_RE = re.compile(r"\\includegraphics(?:\[(?P<opt>[^\]]*)\])?\{(?P<path>[^}]*)\}")


def _width_pct(opt: str) -> int:
    m = re.search(r"width\s*=\s*([\d.]*)\s*\\linewidth", opt or "")
    if not m:
        return 100
    return int(round(float(m.group(1) or 1.0) * 100))


def _center_block(match: re.Match) -> str:
    inner = match.group(1)
    parts = []
    for g in GRAPHIC_RE.finditer(inner):
        src = g.group("path").lstrip("./").replace(" ", "%20")
        parts.append(f'<img src="{src}" width="{_width_pct(g.group("opt"))}%">')
    caption = " ".join(
        re.sub(r"\\small\s*", "", line).strip()
        for line in GRAPHIC_RE.sub("", inner).splitlines()
        if line.strip()
    ).strip()
    if caption:
        parts.append(f"<br><sub><i>{caption}</i></sub>")
    return "<p align=\"center\">\n" + "\n".join(parts) + "\n</p>"


def convert_md(path: Path, demote: int = 2) -> str:
    """Turn a pandoc/LaTeX-flavoured .md write-up into GitHub Markdown."""
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"\A---\n.*?\n---\n", "", text, flags=re.S)      # yaml frontmatter
    text = CENTER_RE.sub(_center_block, text)
    text = GRAPHIC_RE.sub(
        lambda g: f'<img src="{g.group("path").lstrip("./").replace(" ", "%20")}" '
                  f'width="{_width_pct(g.group("opt"))}%">',
        text,
    )
    text = re.sub(r"^(#+)", lambda m: "#" * demote + m.group(1), text, flags=re.M)
    return text.strip()


# --------------------------------------------------------------------------
# code inventory
# --------------------------------------------------------------------------

HOUSEKEEPING = re.compile(
    r"^(?:(?:clear|clc|close(?:\s+all)?|format\s+\w+|warning\s+\w+)\s*[;,]?\s*)+$")


def describe_m(path: Path) -> str:
    """Best-effort one-liner for a MATLAB file: header comment, else signature."""
    header: list[str] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if not s:
            if header:
                break
            continue
        if s.startswith("%"):
            body = s.lstrip("%").strip()
            if not body or set(body) <= {"-", "=", "*"}:
                break
            header.append(body)
            if len(header) == 3:
                break
            continue
        if header:
            break
        if HOUSEKEEPING.match(s):      # `clear; clc; close all;` preamble
            continue
        if s.startswith("function"):
            return "`" + re.sub(r"^function\s+", "", s).rstrip(";") + "`"
        return "MATLAB script."
    if header:
        text = " ".join(header)
        return text if len(text) <= 140 else text[:137].rstrip(" ,;") + "..."
    return "MATLAB script."


def code_table(folder: Path, problem: dict) -> str:
    ms = sorted(folder.glob("*.m"), key=lambda p: p.name.lower())
    if not ms:
        return ""
    overrides = problem.get("files", {})
    entry = problem.get("entry")
    rows = ["| File | What it does |", "| --- | --- |"]
    for m in ms:
        desc = (overrides.get(m.name) or describe_m(m)).replace("|", "\\|")
        if m.name == entry:
            desc = f"**Entry point.** {desc}"
        rows.append(f"| [`{m.name}`]({rel(m, folder)}) | {desc} |")
    subdirs = sorted(d for d in folder.iterdir()
                     if d.is_dir() and not d.name.startswith(".") and d.name != "imgs")
    table = "\n".join(rows)
    if subdirs:
        extra = "\n".join(f"- [`{d.name}/`]({rel(d, folder)})" for d in subdirs)
        table += "\n\nAlso in this folder:\n\n" + extra
    return table


# --------------------------------------------------------------------------
# README rendering
# --------------------------------------------------------------------------

def label(problem: dict) -> str:
    nums = problem.get("numbers") or []
    if not nums:
        return problem["title"]
    if len(nums) == 1:
        return f"P{nums[0]} - {problem['title']}"
    return f"P{nums[0]}-{nums[-1]} - {problem['title']}"


def build_problem_readme(problem: dict, dpi: int, do_compile: bool) -> tuple[Path, str]:
    folder = ROOT / problem["dir"]
    report = discover_report(folder)
    if do_compile:
        report["pdf"] = compile_typst(report["source"], report["pdf"])

    out = [BANNER, "", f"# {label(problem)}", "", problem["blurb"], ""]

    links = ["[&larr; All problems](../README.md)"]
    if report["pdf"]:
        links.append(f"[Report (PDF)]({rel(report['pdf'], folder)})")
    if report["source"] is not None and report["source"] != report["pdf"]:
        kind = "Typst source" if report["source"].suffix == ".typ" else "Markdown source"
        links.append(f"[{kind}]({rel(report['source'], folder)})")
    out += [" &middot; ".join(links), ""]

    code = code_table(folder, problem)
    if code:
        out += ["## Code", "", code, ""]

    # --- the write-up itself -------------------------------------------------
    if report["pdf"]:
        pages = rasterise(report["pdf"], dpi)
        if pages:
            out += ["## Report", ""]
            for i, page in enumerate(pages, 1):
                out += [f"![Page {i} of {report['pdf'].name}]({rel(page, folder)})", ""]
    elif report["source"] is not None and report["source"].suffix == ".md":
        out += ["## Report", "", convert_md(report["source"], demote=2), ""]

    if report["extras"]:
        out += ["## Supplementary", ""]
        for extra in report["extras"]:
            out += [f"### {extra.stem}", ""]
            if extra.suffix == ".pdf":
                for i, page in enumerate(rasterise(extra, dpi), 1):
                    out += [f"![{extra.stem} page {i}]({rel(page, folder)})", ""]
            else:
                out += [convert_md(extra, demote=3), ""]

    return folder / "README.md", "\n".join(out).rstrip() + "\n"


def build_root_readme(meta: dict) -> tuple[Path, str]:
    course, problems = meta["course"], meta["problems"]
    out = [BANNER, "", f"# {course['name']}", "",
           f"Coursework for {course['code']} with {course['instructor']} at "
           f"{course['university']}. MATLAB code and write-ups by {course['author']}.", "",
           "Each folder has its own README with the write-up inlined.", "",
           "| # | Problem | Report |", "| --- | --- | --- |"]
    for p in problems:
        folder = ROOT / p["dir"]
        nums = p.get("numbers") or []
        num = "-" if not nums else (str(nums[0]) if len(nums) == 1 else f"{nums[0]}-{nums[-1]}")
        report = discover_report(folder)
        link = f"[PDF]({rel(report['pdf'], ROOT)})" if report["pdf"] else "in README"
        out.append(f"| {num} | [{p['title']}]({p['dir']}/README.md) | {link} |")
    out += ["",
            "## Regenerating", "",
            "Every `README.md` here is generated. Report PDFs are rasterised into each "
            f"folder's `{PAGES_DIR}/` directory and inlined.", "",
            "```bash",
            "python3 tools/build_readmes.py --compile",
            "```", "",
            "Titles and blurbs live in [`tools/problems.json`](tools/problems.json). "
            "Needs `poppler`; `--compile` also needs `typst`.", ""]
    return ROOT / "README.md", "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--compile", action="store_true",
                    help="recompile .typ reports whose PDF is stale")
    ap.add_argument("--dpi", type=int, default=150, help="report page render DPI")
    ap.add_argument("--check", action="store_true",
                    help="fail if any generated README would change")
    args = ap.parse_args()

    meta = json.loads(META.read_text(encoding="utf-8"))

    known = {p["dir"] for p in meta["problems"]}
    on_disk = {d.name for d in ROOT.iterdir()
               if d.is_dir() and not d.name.startswith(".") and d.name != "tools"}
    for missing in sorted(on_disk - known):
        print(f"! {missing}/ is not listed in tools/problems.json", file=sys.stderr)
    for ghost in sorted(known - on_disk):
        print(f"! {ghost}/ is listed in tools/problems.json but does not exist", file=sys.stderr)

    outputs = []
    for problem in meta["problems"]:
        if problem["dir"] not in on_disk:
            continue
        print(f"{problem['dir']}/")
        outputs.append(build_problem_readme(problem, args.dpi, args.compile))
    print("README.md")
    outputs.append(build_root_readme(meta))

    stale = []
    for path, text in outputs:
        old = path.read_text(encoding="utf-8") if path.exists() else None
        if old == text:
            continue
        stale.append(path)
        if not args.check:
            path.write_text(text, encoding="utf-8")

    if args.check and stale:
        print("\nout of date:", file=sys.stderr)
        for p in stale:
            print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
        return 1
    print(f"\n{len(stale)} file(s) {'stale' if args.check else 'written'}, "
          f"{len(outputs) - len(stale)} unchanged.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
